queue_inventory_upload:
  every: 1h
  # you can use rufus-scheduler "every" syntax in place of cron if you prefer
  # every: 1h
  # By default the job name (hash key) will be taken as worker class name.
  # If you want to have a different job name and class name, provide the 'class' option
  class: "LDAutomaticallyBulkImportSolitaire"
  queue: high
  args:
  description: "This job uploads inventory for all the suppliers into Liquid Diamonds"

get_and_modify_hk_inventory:
  every: 1h
  class: "LDGetAndModifyHKInventory"
  queue: high
  args:
  description: "This job downloads HK inventory and prepares the file for upload to LD server"

get_kc_inventory:
  every: 1h
  class: "LDGetKCInventory"
  queue: high
  args:
  description: "This job downloads KC inventory and prepares the file for upload to LD server"
